### ISSUE TITLE
Query: Possible to customise the "Add page" button label

### ISSUE THREAD

**Issue by Whyglobaleyes** [dregad/dokuwiki-plugin-addnewpage#108]
Hello Everyone,

Is there any possibility of over-riding the text shown on the Add Page button please. 

I intend to have a few buttons on the same page allowing me to quickly create new pages in different namespaces/ with different templates. 
* With the current code I've got two buttons on the page that look identical:
```
  {{NEWPAGE>journal:%Y.%m.%d?autopage}}
  {{NEWPAGE>log:%Y.%m.%d?autopage}}
```
* What I'd like is something along the lines of:
```
  {{NEWPAGE>journal:%Y.%m.%d?autopage?label=New_Journal_Page}}
  {{NEWPAGE>log:%Y.%m.%d?autopage?label=New_Log_Page}}
```

Is this already a thing, is there a work around I can do or would this be a feature request please?
Thanks in advance.

**Comment by dregad** [comment]
It is currently not possible to customize the button's label, it is defined as a localized string:

https://github.com/dregad/dokuwiki-plugin-addnewpage/blob/86f7e2d566557c310d60afe4ff8052fb2fdaa2df/lang/en/lang.php#L7 

You could change the label in your language file(s), but it would apply to all NEWPAGE forms so that's not what you want.

It should not be too difficult to enable custom labels as you suggest.
