### ISSUE TITLE
Plugin is useless after update - users cannot create pages

### ISSUE THREAD

**Issue by Ulmoll** [dregad/dokuwiki-plugin-addnewpage#110]
Since the new update from November 16, 2024, users have not been able to create new pages. 

The plugin tries to create the page above the actual namespace. Of course, the users have no rights for this in the ACL.

This makes the plugin currently useless.

**Comment by ludenticus** [comment]
I can confirm this bug. Latest update makes dokuwiki useless for the creation of new pages (working on a team)

**Comment by ludenticus** [comment]
Temporal workaround: uninstall and manually install last version.

**Comment by ProjectsKoryHasWorkedOn** [comment]
In the interim, could also use
https://www.dokuwiki.org/plugin:addnewpagedeluxe?s[]=namespace

**Comment by sz10101** [comment]
Had to revert back to the 11/8 release.  @splitbrain, this release is broken and @dregad - You should probably revert this back before others get burned by this bug.   @ProjectsKoryHasWorkedOn, thanks - that substitution of _addnewpagedeluxe_ is certainly an option but I just reverted to the prior working release as a temporary workaround.

@dregad has asked the author why he decided to fork the code and identify it as "deluxe" with no response to date.  Seems like a disquieting practice (to me) to publish a fork and be unresponsive to the original project author when pull requests are an option.   
 But this has now been 4 weeks since the breaking release was published and there doesn't appear to be any progress.

Looking forward to a fix.

**Comment by dregad** [comment]
Hi guys, apologies for the silence, for some strange reason I never received any notifications for this until @sz10101 pinged me in the above post (thanks for the heads up).

I'll have a look at it.

Until then, installing the previous version is the correct workaround.

**Comment by dregad** [comment]
I just released [2024-12-24](https://github.com/dregad/dokuwiki-plugin-addnewpage/releases/tag/2024-12-24) which should hopefully fix the problem.

Let me know if it still does not work.

**Comment by sz10101** [comment]
Worked like a charm! Thank you Damien! Merry Christmas to you as well @dregad 

-Steve

**Comment by dregad** [comment]
Thanks for the feedback
