### ISSUE TITLE
{{NEWPAGE>foo:@INPUT@:start}} syntax does not work (Jackrum, current versions)

### ISSUE THREAD

**Issue by Chris75forumname** [dregad/dokuwiki-plugin-addnewpage#98]
`{{NEWPAGE>foo:@INPUT@:start}}` syntax (taken from the documentation) does not work (as described in the documentation).
Placeholder `@INPUT@` is not replaced, resulting in new page ids, like so: `/doku.php?id=foo:input:start:newpage`. (tested with Jackrum and current version of plugin)

**Comment by stvoigt** [comment]
Same here...

**Comment by cblte** [comment]
Running Kaos now and this is still an issue.

**Comment by gnoownow10** [comment]
> Runnng Kaos:
> 
> same with: `{{NEWPAGE>journal:%Y-%m-%d?autopage}}`
> 
> this turns to: `journal:y-_m-_d_autopage:newpage`
> 
> and the `autopage` Option does not work as well. I still have to give input

Same here. Has this feature ever been implemented in the first place?

**Comment by jonathanwgebb** [comment]
Still really hoping for a fix to use @INPUT@. my desire is be able to create new directories on the homepage of my wiki with.
{{NEWPAGE>@INPUT@:homepage}}

**Comment by jonathanwgebb** [comment]
Found a way to fix this, not the prettiest, but works. In the file script.js, the parsed and filtered strings of the namespace directory and the page name are merged then a new page is created. my solution is to change line 22.

turn `var id = ns.val()+":"+title.val();`

into
![image](https://github.com/dregad/dokuwiki-plugin-addnewpage/assets/173375628/e2cde1ba-0f82-4af9-9757-7f8f87ef54df)
This will replace "userinput" in the {{NEWPAGE>userinput:hompage}} with the "title" you entered and then not include the title at the end of string. Make this flag whatever you want. because this modification is after the PHP syntax, the "@'s" are already removed from the string and it is lowercased, hence why I made a custom flag of "userinput". I am not good enough at PHP to find the missing piece in the PHP side of this plugin. That is the better solution if someone can hunt it down.

**Comment by cblte** [comment]
Will this ever get fixed?

**Comment by Fabien4941** [comment]
Same here, @PAGE@ not works.

**Comment by dregad** [comment]
These features were actually part of #72. The PR had merge conflicts, which I managed to resolve (or so I hope), but I never managed to find the time perform the required testing.

The code is available here #102 so if you guys are able and willing to test and confirm that it works as expected, it would be appreciated.

Please post your feedback in the PR.
